# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: puzzle_unsolved.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'puzzle_unsolved.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15puzzle_unsolved.proto\"\x14\n\x04\x43lue\x12\x0c\n\x04\x63lue\x18\x01 \x01(\r\"\x16\n\x05\x42lock\x12\r\n\x05\x62lock\x18\x01 \x01(\t\"6\n\x03Row\x12\x16\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x06.Block\x12\x17\n\x08row_clue\x18\x02 \x01(\x0b\x32\x05.Clue\"\x1a\n\x04Grid\x12\x12\n\x04rows\x18\x01 \x03(\x0b\x32\x04.Row\"+\n\nDimensions\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\"[\n\x06Puzzle\x12\x1f\n\ndimensions\x18\x01 \x01(\x0b\x32\x0b.Dimensions\x12\x1b\n\x0c\x63olumn_clues\x18\x02 \x03(\x0b\x32\x05.Clue\x12\x13\n\x04grid\x18\x03 \x01(\x0b\x32\x05.Grid\"A\n\nPuzzleFile\x12\x19\n\x11number_of_puzzles\x18\x01 \x01(\r\x12\x18\n\x07puzzles\x18\x02 \x03(\x0b\x32\x07.Puzzleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'puzzle_unsolved_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLUE']._serialized_start=25
  _globals['_CLUE']._serialized_end=45
  _globals['_BLOCK']._serialized_start=47
  _globals['_BLOCK']._serialized_end=69
  _globals['_ROW']._serialized_start=71
  _globals['_ROW']._serialized_end=125
  _globals['_GRID']._serialized_start=127
  _globals['_GRID']._serialized_end=153
  _globals['_DIMENSIONS']._serialized_start=155
  _globals['_DIMENSIONS']._serialized_end=198
  _globals['_PUZZLE']._serialized_start=200
  _globals['_PUZZLE']._serialized_end=291
  _globals['_PUZZLEFILE']._serialized_start=293
  _globals['_PUZZLEFILE']._serialized_end=358
# @@protoc_insertion_point(module_scope)
